### PR TITLE
Improved code quality.

### PR DESCRIPTION
**Pull request by fragalcer**

### CODE REVIEW

**Comment by jsquyres** [comment]
Greetings @fragalcer, and thanks for the contributions!

Can I ask what these commits are intended for?  I notice you changed a lot of our whitespace style, and you reverted one of my commits.  Can you explain a bit more than "Improved code quality"?

Thanks!

**Comment by fragalcer** [comment]
> Greetings @fragalcer, and thanks for the contributions!
> 
> Can I ask what these commits are intended for? I notice you changed a lot of our whitespace style, and you reverted one of my commits. Can you explain a bit more than "Improved code quality"?
> 
> Thanks!

@jsquyres Yes, thank you for that. I only changed the code style to be more similar to pep 8 coding styling for python. I also removed some unnecessary code (there was a duplicated function).
I can see the code is used for a database. I couldn't find tests, and couldn't run the code in my computer. Would you like me to run the code locally in my computer? How can I make sure my changes are working fine?
I really would like to help you more :)

**Comment by jsquyres** [comment]
Cool.  Sorry for the delay in replying -- my work week got away from me...

Let me give a little explanation here.

## Background

We're a small Catholic church in Louisville, KY, USA.  There's a bunch of us tech volunteers; we donate time and code to help the administrative functions of the church.  Much of the Python here in this git repository deals with the main parishioner database that the church uses: https://www.acstechnologies.com/parish-data/. We treat that database as the Single Source Of Truth -- all changes to database content are made through the PDS GUI that the parish staff use.

PDS is a mature system, but uses a very old back-end database: the Borland Database Engine (BDE).  To that end, we run a cron job every 15 minutes to use https://github.com/jsquyres/pxlib-and-pxview to export the table data files from the ancient back-end database to an SQLite3 database (if you care, I gave a short presentation about this to a local open source meetup group a few years ago.  [There's not a whole lot of details, but it's a brief summary](https://docs.google.com/presentation/d/1S_FXvyxvMWHwqQdnW8QBI-Jb6VWsEEVciHQXGz6HuAs/edit#slide=id.p) ).  From there, we can run all kinds of Python that can directly read the SQLite3 database.  Since the database is relatively small, you probably noticed that `PDSChurch.py` just reads in the entire database and puts it into two top-level data structures: Families and Members.

The various Python scripts then just use that data for a bunch of purposes:

* Generate Google spreadsheets
* Populate and synchronize Google Groups memberships
* Run the eStewardship drive
* ...etc.

Honestly, exporting the database to SQLite every 15 minutes is a little crude, but given the constraints we have (i.e., we _have_ to use PDS which: 1. uses the ancient BDE database format, and 2. has no ability to hook in actions/events when certain trigger events occur), having a bunch of automation that reads and reacts to the database content every 15 minutes is a simple model that is relatively straightforward to maintain over time.  It has served us well.

## Availability of the databse

I'm sorry, I can't share the database with you.  It's both a proprietary product that we don't own/control, and we can't share all of our parishioner data, either.  ☹️ 

We don't have any CI setup, either -- since this is a fairly small operation, we haven't had the availability to setup a dummy environment for CI and then written a bunch of tests.  Additionally, the company that maintains PDS is in the middle of converting the ancient-back end database to a new, modern (but still proprietary) database: DBISAM.  We're expecting that change within the next 6-12 months.

At a minimum, this will end up changing `PDS.py` and `PDSChurch.py`.  It may have deeper impacts that that, too.

## Local changes

I deeply appreciate the fact that you're providing us with some updates -- thank you!

I assume that you chose us because we are a Hacktoberfest repo.  I hope we can help you get to 4 (or more!) accepted PRs!  😄 

I think we're ok with our whitespace style -- I don't think we need to piecemeal (or wholesale) change all of our whitespace style to PEP.

That being said, typos / fixes, removals of redundant code, ... all of these are awesome.  Thanks!

Can you slice out the whitespace changes and leave just the code fixes / typo fixes / other improvements?  E.g., this PR contains a confusing double commit of one of my prior commits and then reverts it.  I don't think we want those commits included in the PR when we merge.

If you need some git guidance on how to do that, let me know -- happy to help.

**Comment by fragalcer** [comment]
Dear @jsquyres, thank you for your detailed response.

I will close this PR, and I am going to open a new one with a few improvements.

Thank you so much for your help. I hope my pull requests are useful for you.

Kind Regards,

@fragalcer

**Comment by jsquyres** [comment]
No problem, thanks for helping out!

BTW, know that you don't have to close PRs to update them.  PR's just show the current status of a branch from a given repo (e.g., your fork).  If you update that fork, the PR will automatically update.  The easiest way to see this is to push new commits to the branch.  But you can change history / force push and it will update the PR, too.

**Pull request closed without merging**
